"""
Granthom Rasavan — Layout Generation Pipeline
==============================================
Single source of truth: layout/granthom_rasavan_v1.2.json

Reads:
    layout/granthom_rasavan_v1.2.json   — key assignments (source of truth)
    data/character_frequencies.csv      — corpus frequency data
    data/effort_scores.csv              — Colemak Mod-DH effort scores

Generates (auto-generated — do not edit manually):
    data/key_assignment.csv             — human-readable key map
    layout/config/linux/ml_granthom_rasavan  — XKB symbols file stub

Usage:
    python scripts/generate.py

Requirements:
    Python 3.7+  —  no external dependencies

"""

import json
import csv
import sys
from pathlib import Path
from datetime import datetime

# ─────────────────────────────────────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────────────────────────────────────

ROOT         = Path(__file__).parent.parent
LAYOUT_JSON  = ROOT / "layout" / "granthom_rasavan_v1.2.json"
FREQ_CSV     = ROOT / "data" / "character_frequencies.csv"
EFFORT_CSV   = ROOT / "data" / "effort_scores.csv"
KEY_CSV      = ROOT / "data" / "key_assignment.csv"
XKB_OUT      = ROOT / "layout" / "config" / "linux" / "ml_granthom_rasavan"

# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED FILE HEADERS
# ─────────────────────────────────────────────────────────────────────────────

def csv_autogen_header(source: str) -> list[str]:
    """Returns header rows to prepend to every generated CSV."""
    return [
        ["# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
        ["# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY"],
        ["# Generated by : scripts/generate.py"],
        [f"# Generated on : {datetime.now().strftime('%Y-%m-%d %H:%M')}"],
        [f"# Source       : {source}"],
        ["# To update    : edit the source file, then run: python scripts/generate.py"],
        ["# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"],
        [],
    ]

def xkb_autogen_header(source: str) -> list[str]:
    """Returns header lines to prepend to the XKB symbols file."""
    return [
        "// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        "// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY",
        "// Generated by : scripts/generate.py",
        f"// Generated on : {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"// Source       : {source}",
        "// To update    : edit the source file, then run: python scripts/generate.py",
        "// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        "//",
        "// Granthom Rasavan (ഗ്രന്ഥം രസവാൻ) — Malayalam Keyboard Layout",
        "// XKB Symbols File — Linux keyboard configuration",
        "//",
        "// Layer 1 (Normal)     : Base consonant / vowel matra",
        "// Layer 2 (Shift)      : Consonant+virama / independent vowel",
        "// Layer 3 (AltGr)      : Chillu / Malayalam digit / specialist",
        "// Layer 4 (AltGr+Sh)  : Rare / archaic / Grantha",
        "// Caps Lock            : English QWERTY toggle",
        "//",
        "// NOTE: Virama-attached consonants (Shift layer) output two codepoints.",
        "// Full implementation requires compose rules for these sequences.",
        "// See layout/config/linux/README.md for implementation notes.",
        "//",
    ]

# ─────────────────────────────────────────────────────────────────────────────
# LOADERS
# ─────────────────────────────────────────────────────────────────────────────

def load_layout(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)

def load_frequencies(path: Path) -> dict:
    """Returns dict keyed by normal_layer character → row dict.
    Skips comment lines starting with #."""
    freq = {}
    with open(path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(row for row in f if not row.startswith("#"))
        for row in reader:
            freq[row["normal_layer"]] = row
    return freq

def load_effort_scores(path: Path) -> dict:
    """Returns dict keyed by key (lowercase) → row dict.
    Skips comment lines starting with #."""
    effort = {}
    with open(path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(row for row in f if not row.startswith("#"))
        for row in reader:
            effort[row["key"].lower()] = row
    return effort

# ─────────────────────────────────────────────────────────────────────────────
# EXTRACT CHARACTER KEYS FROM JSON
# ─────────────────────────────────────────────────────────────────────────────

def extract_keys(layout: dict) -> list[dict]:
    """Extract all character keys from layout JSON (skip modifiers)."""
    keys = []
    for key_id, key_data in layout.get("placed", {}).items():
        if key_data.get("isMod"):
            continue
        ph = key_data.get("ph", "").lower().strip()
        if not ph:
            continue
        keys.append({
            "key_id":   key_id,
            "ph":       ph,
            "normal":   key_data.get("br", ""),
            "shift":    key_data.get("tr", ""),
            "altgr":    key_data.get("bl", ""),
            "altgr_sh": key_data.get("tl", ""),
            "label":    key_data.get("lb", ""),
        })
    return keys

# ─────────────────────────────────────────────────────────────────────────────
# GENERATE KEY ASSIGNMENT CSV
# ─────────────────────────────────────────────────────────────────────────────

def generate_key_csv(
    keys: list[dict],
    freq: dict,
    effort: dict,
    out_path: Path,
    wes: float,
):
    fieldnames = [
        "ph", "label",
        "normal", "shift", "altgr", "altgr_shift",
        "effort_score", "effort_rank", "hand", "row", "finger",
        "group_id", "group_type", "raw_count", "frequency_pct",
        "weighted_contribution",
    ]

    rows = []
    for k in keys:
        ph  = k["ph"]
        e   = effort.get(ph, {})
        f   = freq.get(k["normal"], {})

        # Weighted contribution = effort_score × frequency_pct
        # Shows each key's individual contribution to the overall WES
        try:
            e_score = float(e.get("effort_score", 0))
            f_pct   = float(f.get("frequency_pct", 0))
            contribution = round(e_score * f_pct, 6)
        except (ValueError, TypeError):
            contribution = ""

        rows.append({
            "ph":                   ph,
            "label":                k["label"],
            "normal":               k["normal"],
            "shift":                k["shift"],
            "altgr":                k["altgr"],
            "altgr_shift":          k["altgr_sh"],
            "effort_score":         e.get("effort_score", ""),
            "effort_rank":          e.get("rank", ""),
            "hand":                 e.get("hand", ""),
            "row":                  e.get("row", ""),
            "finger":               e.get("finger", ""),
            "group_id":             f.get("group_id", ""),
            "group_type":           f.get("group_type", ""),
            "raw_count":            f.get("raw_count", ""),
            "frequency_pct":        f.get("frequency_pct", ""),
            "weighted_contribution": contribution,
        })

    # Sort by effort rank ascending, then frequency descending
    rows.sort(key=lambda r: (
        int(r["effort_rank"]) if r["effort_rank"] else 99,
        -float(r["frequency_pct"]) if r["frequency_pct"] else 0
    ))

    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)

        # Auto-generated file header
        for line in csv_autogen_header("layout/granthom_rasavan_v1.2.json"):
            writer.writerow(line)

        # WES score and formula block
        writer.writerow(["# ── KEYBOARD SCORE (Weighted Effort Score) ─────────────────────────"])
        writer.writerow(["#"])
        writer.writerow(["# Formula (Colemak Mod-DH model):"])
        writer.writerow(["#"])
        writer.writerow(["#   WES = Σ ( effort_score_i × frequency_pct_i )"])
        writer.writerow(["#             ─────────────────────────────────"])
        writer.writerow(["#                   Σ ( frequency_pct_i )"])
        writer.writerow(["#"])
        writer.writerow(["# Where:"])
        writer.writerow(["#   effort_score_i  = Colemak Mod-DH score for the key assigned to group i"])
        writer.writerow(["#                     (from data/effort_scores.csv)"])
        writer.writerow(["#   frequency_pct_i = corpus frequency % of character group i"])
        writer.writerow(["#                     (from data/character_frequencies.csv)"])
        writer.writerow(["#"])
        writer.writerow(["# Effort scores reflect: row penalty + finger strength + lateral motion"])
        writer.writerow(["# penalty (Fitts's Law). Home row index finger = 1.0 (minimum)."])
        writer.writerow(["# Source: https://colemakmods.github.io/mod-dh/"])
        writer.writerow(["#"])
        writer.writerow([f"# WES (this layout) = {wes:.4f}"])
        writer.writerow(["#"])
        writer.writerow(["# Reference scores:"])
        writer.writerow(["#   Theoretical minimum   : 1.0000  (home row only)"])
        writer.writerow(["#   Granthom Rasavan v1.2  : " + f"{wes:.4f}  (this layout)"])
        writer.writerow(["#   Granthom Rasavan v3.0  : 1.8060  (analysis optimum, pending testing)"])
        writer.writerow(["#   Colemak Mod-DH (English): ~1.800"])
        writer.writerow(["#   InScript Malayalam     : ~2.200  (estimated)"])
        writer.writerow(["#   QWERTY (English)       : ~3.000"])
        writer.writerow(["#"])
        writer.writerow(["# weighted_contribution column = effort_score × frequency_pct per key"])
        writer.writerow(["# Sum of weighted_contribution / sum of frequency_pct = WES above"])
        writer.writerow(["# ────────────────────────────────────────────────────────────────────"])
        writer.writerow([])

        # Data
        dict_writer = csv.DictWriter(f, fieldnames=fieldnames)
        dict_writer.writeheader()
        dict_writer.writerows(rows)

    print(f"  Generated : {out_path.relative_to(ROOT)}")
    print(f"  Rows      : {len(rows)}")
    print(f"  WES       : {wes:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# GENERATE XKB SYMBOLS FILE
# ─────────────────────────────────────────────────────────────────────────────

def generate_xkb(keys: list[dict], out_path: Path):
    """Generate XKB symbols file stub from layout JSON."""

    key_map = {k["ph"]: k for k in keys}

    def xkb_char(ch: str) -> str:
        if not ch or ch == " ":
            return "space"
        cp = ord(ch[0])
        return f"U{cp:04X}"

    xkb_key_names = {
        "`": "TLDE", "1": "AE01", "2": "AE02", "3": "AE03",
        "4": "AE04", "5": "AE05", "6": "AE06", "7": "AE07",
        "8": "AE08", "9": "AE09", "0": "AE10", "-": "AE11", "=": "AE12",
        "q": "AD01", "w": "AD02", "e": "AD03", "r": "AD04", "t": "AD05",
        "y": "AD06", "u": "AD07", "i": "AD08", "o": "AD09", "p": "AD10",
        "[": "AD11", "]": "AD12", "\\": "BKSL",
        "a": "AC01", "s": "AC02", "d": "AC03", "f": "AC04", "g": "AC05",
        "h": "AC06", "j": "AC07", "k": "AC08", "l": "AC09", ";": "AC10",
        "'": "AC11",
        "z": "AB01", "x": "AB02", "c": "AB03", "v": "AB04", "b": "AB05",
        "n": "AB06", "m": "AB07", ",": "AB08", ".": "AB09", "/": "AB10",
    }

    lines = xkb_autogen_header("layout/granthom_rasavan_v1.2.json")
    lines += [
        "",
        "default partial alphanumeric_keys",
        'xkb_symbols "granthom_rasavan" {',
        "",
        '    name[Group1] = "Malayalam - Granthom Rasavan";',
        "",
        "    // Caps Lock: reassigned to English QWERTY toggle",
        "    // (configure via XKB option or desktop environment)",
        "",
    ]

    for ph, xkb_name in xkb_key_names.items():
        k = key_map.get(ph)
        if not k:
            continue
        l1 = xkb_char(k["normal"])
        l2 = xkb_char(k["shift"])
        l3 = xkb_char(k["altgr"])    if k["altgr"]    else "VoidSymbol"
        l4 = xkb_char(k["altgr_sh"]) if k["altgr_sh"] else "VoidSymbol"
        comment = f"// {k['normal']} | {k['shift']} | {k['altgr']} | {k['altgr_sh']}"
        lines.append(
            f"    key <{xkb_name}> {{ [ {l1}, {l2}, {l3}, {l4} ] }};  {comment}"
        )

    lines += [
        "",
        "    // AltGr (ISO Level 3) — Right Alt key",
        '    include "level3(ralt_switch)"',
        "",
        "};",
        "",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"  Generated : {out_path.relative_to(ROOT)}")

# ─────────────────────────────────────────────────────────────────────────────
# COMPUTE WES
# ─────────────────────────────────────────────────────────────────────────────

def compute_wes(keys: list[dict], freq: dict, effort: dict) -> float:
    """Compute Weighted Effort Score from current key assignment."""
    total_count  = 0
    weighted_sum = 0.0
    for k in keys:
        e_row = effort.get(k["ph"], {})
        score_str = e_row.get("effort_score", "")
        if not score_str:
            continue
        f_row = freq.get(k["normal"], {})
        count_str = f_row.get("raw_count", "")
        if not count_str:
            continue
        try:
            score = float(score_str)
            count = int(count_str)
        except ValueError:
            continue
        weighted_sum += score * count
        total_count  += count
    return weighted_sum / total_count if total_count else 0.0

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    print()
    print("Granthom Rasavan — Layout Generation Pipeline")
    print("=" * 50)

    # Verify input files exist
    for path in [LAYOUT_JSON, FREQ_CSV, EFFORT_CSV]:
        if not path.exists():
            print(f"ERROR: File not found: {path}")
            sys.exit(1)

    print(f"  Source     : {LAYOUT_JSON.name}")
    print(f"  Frequencies: {FREQ_CSV.name}")
    print(f"  Effort     : {EFFORT_CSV.name}")

    layout = load_layout(LAYOUT_JSON)
    freq   = load_frequencies(FREQ_CSV)
    effort = load_effort_scores(EFFORT_CSV)
    keys   = extract_keys(layout)

    print(f"  Keys found : {len(keys)} character keys")

    print("\n[1] Computing Weighted Effort Score ...")
    wes = compute_wes(keys, freq, effort)
    if wes:
        print(f"  WES = {wes:.4f}")
    else:
        print("  WES = could not compute (check frequency / effort data)")

    print("\n[2] Generating key_assignment.csv ...")
    generate_key_csv(keys, freq, effort, KEY_CSV, wes)

    print("\n[3] Generating XKB symbols file ...")
    generate_xkb(keys, XKB_OUT)

    print()
    print("Done.")
    print("Generated files are marked AUTO-GENERATED.")
    print("Edit layout JSON → re-run this script → commit JSON + generated files.")

if __name__ == "__main__":
    main()